davidmhewitt/torrential

AUTHORS
data/128/com.github.davidmhewitt.torrential.svg
data/16/com.github.davidmhewitt.torrential.svg
data/24/com.github.davidmhewitt.torrential.svg
data/32/com.github.davidmhewitt.torrential.svg
data/48/com.github.davidmhewitt.torrential.svg
data/64/com.github.davidmhewitt.torrential.svg
data/symbolic/com.github.davidmhewitt.torrential-symbolic.svg

Some new icons for you, I've added them into the `data` folder, but that's all :)

added icons

---

data/128/com.github.davidmhewitt.torrential.svg
data/16/com.github.davidmhewitt.torrential.svg
data/24/com.github.davidmhewitt.torrential.svg
data/32/com.github.davidmhewitt.torrential.svg
data/48/com.github.davidmhewitt.torrential.svg
data/64/com.github.davidmhewitt.torrential.svg

shrunk file size of the icon svgs

smaller svgs

---

src/Widgets/TorrentListRow.vala

* Use small markup tag
* Use em dash instead of hyphen
* Use symbolic icons
* Adjust margins, column, row spacing
Before:
After:

TorrentListRow.vala: design adjustments

---

po/it.po

Hi, 
I've made and tested this Italian translation
Greetings

Added Italian Translation

---

po/id.po

update bahasa indonesia translation

update bahasa indonesia translation

---

CMakeLists.txt

Support HiDPI icons

---

data/com.github.davidmhewitt.torrential.desktop
po/pt_BR.po

Added translations for your app for Brazilian Portuguese language

Add Brazilian Portuguese translation

---

po/es.po

Spanish translation updated, fixed fuzzy translations. No more untranslated strings either.

Spanish translation updated

---

CMakeLists.txt
src/Dialogs/FileSelectDialog.vala
src/Torrent.vala
src/Widgets/FileSelectTreeView.vala
src/Widgets/TorrentListBox.vala
src/Widgets/TorrentListRow.vala
vapi/transmission-2.0.vapi

Ability to select which files in a torrent to download

---

data/icons/open-magnet.svg

Manilla magnet icon

---

src/Widgets/TorrentListBox.vala

Remove selected torrent when pressing delete or backspace

---

src/Widgets/TorrentListRow.vala

TorrentListRow: Fix green progressbar when seeding

---

src/Widgets/TorrentListRow.vala

Ellipsize torrent name

---

src/MainWindow.vala
src/PreferencesWindow.vala

Don't use Grid where we mean Box

Replace Grid with Box

---

data/meson.build
data/torrential.metainfo.xml.in
po/extra/POTFILES

* Rename Appdata → Metainfo
* Add `translation`, `branding`, `provides`, `recommends`, and `supports` tags
* Add donation URL
* Use compact OARS
* Re-organize

Metainfo: modernize

---

src/MainWindow.vala
src/Widgets/MultiInfoBar.vala

Use built-in revealed property instead of visible etc

MultiinfoBar: set self revealed

---

src/Widgets/TorrentListBox.vala

Can't subclass ListBox in Gtk 4.
While we're here, make it GObject style and DRY remove action

TorrentListBox: subclass box

---

src/PreferencesWindow.vala

* Code style
* Let widgets determine the window size
* DRY margins
* Reduce indention from 20px to 12px
* Remove some unnecessary properties
* Only update download folder label when that specific setting changes

PreferencesWindow: code style and cleanup

---

src/Application.vala
src/MainWindow.vala

More Gtk4 prep. `get_uris ()` is no longer in FileChooserNative so switch to `get_files ()`.
Is there a better way to create an SList from an array? That seems so silly

MainWindow: add_files takes SList<File>

---

src/Widgets/TorrentListBox.vala

Gtk 4 prep
* don't use `popup_menu.connect` which doesn't exist anymore
* Uses Gtk.PopoverMenu instead of Gtk.Menu

Torrentlistbox popovermenu

---

.github/workflows/main.yml
com.github.davidmhewitt.torrential.yml

Updating to elementary runtime 8 as default elementary apps have already been updated.
Note that this might need some more testing

Update runtime to 8
